import { Analysis, DashboardStats } from '@/types';

export const DEMO_ANALYSIS: Analysis = {
  id: 'demo-analysis-alex-stripe',
  resume_id: 'demo-resume-1',
  job_id: 'demo-job-stripe',
  resume_title: 'Alex Rivera — Senior Backend Resume.pdf',
  job_title: 'Senior Backend Engineer',
  company_name: 'Stripe',
  overall_ats_score: 87.0,
  job_match_score: 82.5,
  keyword_match_score: 84.0,
  quality_score: 88.0,
  summary:
    'Strong ATS compatibility and technical alignment for the Senior Backend Engineer role at Stripe. Detected high proficiency in Python, FastAPI, and PostgreSQL. Closing the cloud architecture and Redis cache clustering gaps will make this a top 5% candidate application.',
  scores: [
    {
      category: 'ATS Compatibility',
      score: 92.0,
      max_score: 100,
      status: 'Excellent',
      explanation: 'Clean single-column layout, standard section titles, and 100% parsable text with zero unreadable nested tables.',
    },
    {
      category: 'Keyword Match',
      score: 84.0,
      max_score: 100,
      status: 'Strong',
      explanation: 'Found 24 out of 28 core technical keywords and framework variants specified in the job description.',
    },
    {
      category: 'Skills Match',
      score: 82.5,
      max_score: 100,
      status: 'Strong',
      explanation: '14 core technical competencies matched; 4 important skill gaps identified in distributed message queuing.',
    },
    {
      category: 'Experience Match',
      score: 85.0,
      max_score: 100,
      status: 'Strong',
      explanation: 'Experience section highlights high-concurrency microservices, sub-45ms latency tuning, and production scale.',
    },
    {
      category: 'Education Match',
      score: 95.0,
      max_score: 100,
      status: 'Excellent',
      explanation: 'B.S. in Computer Science plus AWS Certified Solutions Architect credential recognized.',
    },
    {
      category: 'Formatting Quality',
      score: 92.0,
      max_score: 100,
      status: 'Excellent',
      explanation: 'Consistent typography, clear hierarchical spacing, and standard font styling.',
    },
    {
      category: 'Readability',
      score: 88.0,
      max_score: 100,
      status: 'Strong',
      explanation: 'High information density without visual crowding. Average bullet length is 18-24 words.',
    },
    {
      category: 'Impact',
      score: 86.0,
      max_score: 100,
      status: 'Strong',
      explanation: '7 quantified metrics detected including 5M+ requests, 42% latency reduction, and sub-45ms p99 latency.',
    },
  ],
  keywords: [
    { keyword: 'FastAPI', category: 'Already Found', status: 'found', relevance: 'high' },
    { keyword: 'PostgreSQL', category: 'Already Found', status: 'found', relevance: 'high' },
    { keyword: 'Python', category: 'Already Found', status: 'found', relevance: 'high' },
    { keyword: 'REST APIs', category: 'Already Found', status: 'found', relevance: 'high' },
    { keyword: 'Docker', category: 'Already Found', status: 'found', relevance: 'high' },
    { keyword: 'Kubernetes', category: 'Already Found', status: 'found', relevance: 'high' },
    { keyword: 'AWS', category: 'Already Found', status: 'found', relevance: 'high' },
    { keyword: 'Microservices', category: 'Already Found', status: 'found', relevance: 'high' },
    { keyword: 'Distributed Systems', category: 'Critical Missing', status: 'missing', relevance: 'high', section_suggestion: 'Experience' },
    { keyword: 'Kafka', category: 'Critical Missing', status: 'missing', relevance: 'high', section_suggestion: 'Experience' },
    { keyword: 'CI/CD Pipelines', category: 'Already Found', status: 'found', relevance: 'high' },
    { keyword: 'Redis Clustering', category: 'Recommended', status: 'missing', relevance: 'medium', section_suggestion: 'Skills' },
    { keyword: 'Observability', category: 'Recommended', status: 'missing', relevance: 'medium', section_suggestion: 'Projects' },
    { keyword: 'System Design', category: 'Already Found', status: 'found', relevance: 'high' },
  ],
  skills: [
    { skill_name: 'Python', match_percentage: 100, priority: 'Must Have', in_resume: true, in_job: true },
    { skill_name: 'FastAPI', match_percentage: 100, priority: 'Must Have', in_resume: true, in_job: true },
    { skill_name: 'PostgreSQL', match_percentage: 100, priority: 'Must Have', in_resume: true, in_job: true },
    { skill_name: 'Distributed Systems', match_percentage: 35, priority: 'Must Have', in_resume: false, in_job: true },
    { skill_name: 'Kafka / Event Streaming', match_percentage: 20, priority: 'Must Have', in_resume: false, in_job: true },
    { skill_name: 'Docker & Kubernetes', match_percentage: 100, priority: 'Good to Have', in_resume: true, in_job: true },
    { skill_name: 'AWS Cloud Infrastructure', match_percentage: 90, priority: 'Good to Have', in_resume: true, in_job: true },
    { skill_name: 'Redis In-Memory Caching', match_percentage: 85, priority: 'Good to Have', in_resume: true, in_job: true },
    { skill_name: 'Terraform IaC', match_percentage: 75, priority: 'Bonus', in_resume: true, in_job: true },
    { skill_name: 'Datadog / Prometheus', match_percentage: 0, priority: 'Bonus', in_resume: false, in_job: true },
  ],
  issues: [
    {
      severity: 'Passed',
      category: 'Multi-column layout',
      title: 'Single-column structure confirmed',
      description: 'Standard linear flow guarantees seamless parsing across all legacy and modern ATS systems.',
    },
    {
      severity: 'Passed',
      category: 'Section headings',
      title: 'Standard section headings detected',
      description: 'Experience, Education, Skills, and Projects sections use conventional titles.',
    },
    {
      severity: 'Passed',
      category: 'Contact information',
      title: 'Valid email and direct phone detected',
      description: 'Contact details are embedded in normal body text, not buried in headers/footers.',
    },
    {
      severity: 'Warning',
      category: 'Bullet Point Metrics',
      title: 'Two experience bullets lack quantifiable business outcomes',
      description: 'Bullets describe functional responsibilities rather than measured percentage or financial impact.',
      recommendation: 'Rewrite bullet points using the Google XYZ formula: Accomplished [X] measured by [Y] doing [Z].',
    },
    {
      severity: 'Warning',
      category: 'Keywords Density',
      title: 'Distributed Systems terminology underrepresented in recent roles',
      description: 'While microservices are highlighted, core terms like "event sourcing" and "distributed consensus" are absent.',
      recommendation: 'Add distributed systems keywords to your current Senior Backend Engineer role.',
    },
    {
      severity: 'Passed',
      category: 'File readability',
      title: 'Clean PDF text layer verified',
      description: 'PyMuPDF successfully extracted 100% of characters with zero font encoding errors.',
    },
  ],
  recommendations: [
    {
      section: 'Skills',
      priority: 'High',
      title: 'Incorporate Kafka & Distributed Systems keywords',
      action_item: 'Add "Apache Kafka" and "Distributed Event Streaming" into your Technical Skills and recent CloudScale experience.',
    },
    {
      section: 'Experience',
      priority: 'High',
      title: 'Quantify NovaByte Labs bullet points',
      action_item: 'Add specific latency numbers or scale figures (e.g., "supporting 50,000 active users") to the junior engineer role.',
    },
    {
      section: 'Summary',
      priority: 'Medium',
      title: 'Align headline with target role: Senior Backend Engineer',
      action_item: 'Tailor your professional summary to mention Stripe payment infrastructure domains explicitly.',
    },
    {
      section: 'Projects',
      priority: 'Low',
      title: 'Add live GitHub repositories',
      action_item: 'Link directly to open-source contributions or architecture RFCs.',
    },
  ],
  sections_analysis: [
    {
      section_name: 'Summary',
      score: 84.0,
      strengths: ['Concise and authoritative tone', 'Highlights 6+ years of specialized systems experience'],
      issues: ['Does not explicitly state target industry or domain of interest (Payments/FinTech)'],
      recommendations: ['Mention interest in high-scale payments and transaction processing'],
    },
    {
      section_name: 'Experience',
      score: 86.0,
      strengths: ['Strong action verbs (Architected, Engineered, Spearheaded)', 'Excellent sub-45ms latency metric'],
      issues: ['Second job description could have more quantifiable business impact'],
      recommendations: ['Add dollar amounts or throughput percentages to Apex Financial bullets'],
    },
    {
      section_name: 'Skills',
      score: 84.0,
      strengths: ['Clear categorization by Languages, Frameworks, Cloud, Databases'],
      issues: ['Missing Kafka and event streaming queues requested by Stripe'],
      recommendations: ['Group skills into Core Languages, Distributed Databases, and Cloud DevOps'],
    },
    {
      section_name: 'Education',
      score: 95.0,
      strengths: ['Accredited B.S. in Computer Science', 'Clear graduation timeline'],
      issues: [],
      recommendations: ['Keep as is; formatting is optimal for ATS'],
    },
    {
      section_name: 'Certifications',
      score: 92.0,
      strengths: ['AWS Solutions Architect and CKAD credentials provide strong credibility'],
      issues: [],
      recommendations: ['List credential validation URLs where appropriate'],
    },
  ],
  created_at: '2026-10-07T12:00:00Z',
};

export const DEMO_STATS: DashboardStats = {
  total_analyses: 8,
  average_ats_score: 84.2,
  best_match_score: 89.0,
  resumes_improved: 4,
  score_history: [
    { id: '1', date: 'Sep 12', ats_score: 68, match_score: 62, keyword_score: 65 },
    { id: '2', date: 'Sep 18', ats_score: 74, match_score: 71, keyword_score: 70 },
    { id: '3', date: 'Sep 25', ats_score: 79, match_score: 76, keyword_score: 78 },
    { id: '4', date: 'Oct 01', ats_score: 83, match_score: 80, keyword_score: 82 },
    { id: '5', date: 'Oct 04', ats_score: 85, match_score: 81, keyword_score: 84 },
    { id: '6', date: 'Oct 07', ats_score: 87, match_score: 82.5, keyword_score: 84 },
  ],
  top_missing_skills: [
    { skill: 'Apache Kafka', occurrences: 5 },
    { skill: 'Distributed Systems', occurrences: 4 },
    { skill: 'Terraform', occurrences: 3 },
    { skill: 'GraphQL', occurrences: 2 },
    { skill: 'Prometheus', occurrences: 2 },
  ],
  most_frequent_missing_keywords: [
    { keyword: 'Kafka', count: 4 },
    { keyword: 'Event-Driven', count: 3 },
    { keyword: 'Observability', count: 2 },
    { keyword: 'Redis Clustering', count: 2 },
  ],
  suggested_improvements: [
    {
      section: 'Experience',
      priority: 'High',
      title: 'Quantify older bullets with measurable outcomes',
      action: 'Upgrade passive duties into measured accomplishments with % and scale metrics.',
    },
    {
      section: 'Skills',
      priority: 'High',
      title: 'Add Distributed Streaming keywords',
      action: 'Incorporate Kafka and RabbitMQ messaging keywords into your tech stack list.',
    },
    {
      section: 'Summary',
      priority: 'Medium',
      title: 'Target job title alignment',
      action: 'Align your headline directly with the exact job posting title.',
    },
  ],
  recent_analyses: [
    {
      id: 'demo-analysis-alex-stripe',
      resume_id: 'res-1',
      resume_name: 'Alex Rivera — Senior Backend Resume.pdf',
      job_title: 'Senior Backend Engineer',
      company: 'Stripe',
      ats_score: 87.0,
      match_score: 82.5,
      date: 'Oct 07, 2026',
    },
    {
      id: 'analysis-2',
      resume_id: 'res-1',
      resume_name: 'Alex Rivera — Senior Backend Resume.pdf',
      job_title: 'Staff Platform Engineer',
      company: 'Vercel',
      ats_score: 83.5,
      match_score: 80.0,
      date: 'Oct 02, 2026',
    },
    {
      id: 'analysis-3',
      resume_id: 'res-2',
      resume_name: 'Full Stack Systems Resume.pdf',
      job_title: 'Principal Engineer',
      company: 'Datadog',
      ats_score: 79.0,
      match_score: 75.0,
      date: 'Sep 26, 2026',
    },
  ],
};
